version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    command: mongod --smallfiles
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/var/log
      - MONBODB_USER="admin"
      - MONGODB_PASS="pa$$"
